CREATE DATABASE IF NOT EXISTS emp_auth;

USE emp_auth;

CREATE TABLE users(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100),
    password VARCHAR(100),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);